# Generated by hand because automated makemigrations is unavailable in the
# execution environment.

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("files", "0013_page_tinymcemedia"),
    ]

    operations = [
        migrations.CreateModel(
            name="MediaAutoImportRecord",
            fields=[
                ("id", models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("source_path", models.CharField(help_text="Absolute path to the original file on disk.", max_length=2048, unique=True)),
                ("config_name", models.CharField(blank=True, help_text="Identifier of the watch configuration that imported the file.", max_length=100)),
                ("md5sum", models.CharField(blank=True, help_text="Checksum captured after the media file was imported.", max_length=50, null=True)),
                ("imported_at", models.DateTimeField(blank=True, help_text="Timestamp when the media was imported into MediaCMS.", null=True)),
                ("last_seen", models.DateTimeField(auto_now=True, help_text="Timestamp of the last time the watcher encountered the file.")),
                ("media", models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name="auto_import_records", to="files.media")),
            ],
            options={
                "verbose_name": "Watched media import",
                "verbose_name_plural": "Watched media imports",
            },
        ),
        migrations.AddIndex(
            model_name="mediaautoimportrecord",
            index=models.Index(fields=["config_name"], name="files_media_config__4a9a8d_idx"),
        ),
        migrations.AddIndex(
            model_name="mediaautoimportrecord",
            index=models.Index(fields=["imported_at"], name="files_media_import__a0a08c_idx"),
        ),
    ]

